import {AutomaticCalculation} from './consts.autoCalc';

export const FisicsQuestionsType = {
    'Pebble': {
        'type': 36,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'metric': 'g kg⁻¹',
        'name': 'Pebble',
        'label': 'Calhaus',
        'placeholder': 'Informe o valor'
    },
    'Gravel': {
        'type': 37,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'name': 'Gravel',
        'metric': 'g kg⁻¹',
        'label': 'Cascalho',
        'placeholder': 'Informe o valor'
    },
    'ThinEarth': {
        'type': 35,
        'maxLength': 4,
        'inputType': 1,
        'default': 1000,
        'keyboardType': 'number',
        'metric': 'g kg⁻¹',
        'max': 1000,
        'editable': false,
        'name': 'ThinEarth',
        'label': 'Terra fina seca ao ar',
        'placeholder': 'Informe o valor'
    },
    'AreiaGrossa': {
        'type': 45,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'name': 'AreiaGrossa',
        'metric': '2 – 0,2 g kg⁻¹',
        'label': 'Areia Grossa',
        'placeholder': 'Informe o valor'
    },
    'AreiaFina': {
        'type': 46,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'name': 'AreiaFina',
        'metric': '< 0,2 – 0,05 g kg⁻¹',
        'label': 'Areia Fina',
        'placeholder': 'Informe o valor'
    },
    'Silte': {
        'type': 47,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'default': 1000,
        'editable': false,
        'calculation': [AutomaticCalculation.SilteArgila],
        'equalToMaxValueCalc': [this.Argila],
        'name': 'Silte',
        'metric': '< 0,05 – 0,002 g kg⁻¹',
        'label': 'Silte',
        'placeholder': 'Informe o valor'
    },
    'Argila': {
        'type': 48,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'calculation': [AutomaticCalculation.GrauFloculacao, AutomaticCalculation.SilteArgila],
        'name': 'Argila',
        'metric': '< 0,002 g kg⁻¹',
        'label': 'Argila',
        'placeholder': 'Informe o valor'
    },
    'ArgilaDispersaAgua': {
        'type': 49,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'calculation': [AutomaticCalculation.GrauFloculacao],
        'name': 'ArgilaDispersaAgua',
        'metric': 'g kg⁻¹',
        'label': 'Argila dispersa em água',
        'placeholder': 'Informe o valor'
    },
    'GrauFloculacao': {
        'type': 50,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 1000,
        'name': 'GrauFloculacao',
        'metric': '%',
        'label': 'Grau de floculação',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'SilteArgila': {
        'type': 51,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 100,
        'name': 'SilteArgila',
        'label': 'Relação Silte/Argila',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'DensidadeSolo': {
        'type': 42,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 3,
        'calculation': [AutomaticCalculation.PorosidadeTotal],
        'name': 'DensidadeSolo',
        'metric': 'kg dm⁻³',
        'label': 'Densidade do solo',
        'placeholder': 'Informe o valor'
    },
    'DensidadeParticulas': {
        'type': 43,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'calculation': [AutomaticCalculation.PorosidadeTotal],
        'max': 6,
        'name': 'DensidadeParticulas',
        'metric': 'kg dm-³',
        'label': 'Densidade das particulas',
        'placeholder': 'Informe o valor'
    },
    'PorosidadeTotal': {
        'type': 44,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 1,
        'name': 'PorosidadeTotal',
        'metric': 'm³ m⁻³',
        'label': 'Porosidade total',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'ConstantesHidricas01': {
        'type': 39,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 3,
        'name': 'ConstantesHidricas01',
        'metric': 'g kg⁻¹',
        'label': 'Constantes Hídricas (0,01MPa)',
        'placeholder': 'Informe o valor'
    },
    'ConstantesHidricas33': {
        'type': 38,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 3,
        'decimal': 2,
        'name': 'ConstantesHidricas33',
        'metric': 'g kg⁻¹',
        'label': 'Constantes Hídricas (0,033MPa)',
        'placeholder': 'Informe o valor'
    },
    'ConstantesHidricas15': {
        'type': 40,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 3,
        'name': 'ConstantesHidricas15',
        'metric': 'g kg⁻¹',
        'label': 'Constantes Hídricas (1,5MPa)',
        'placeholder': 'Informe o valor'
    },
    'AguaDisponivel': {
        'type': 41,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 3,
        'name': 'AguaDisponivel',
        'metric': '%',
        'label': 'Água disponível',
        'placeholder': 'Informe o valor'
    },
    'EqUmidade': {
        'type': 97,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 3,
        'name': 'EqUmidade',
        'metric': '%',
        'label': 'Equivalente de Umidade',
        'placeholder': 'Informe o valor'
    },
}
