export const ChemistryQuestionsType = {
    'PHAgua': {
        'type': 52,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 14,
        'decimal': 1,
        'name': 'PHAgua',
        'label': 'pH em água (1:2,5)',
        'placeholder': 'Informe o valor'
    },
    'PHKCI': {
        'type': 53,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 14,
        'decimal': 1,
        'name': 'PHKCI',
        'label': 'pH em KCI (1:2,5)',
        'placeholder': 'Informe o valor'
    },
    'C': {
        'type': 66,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        // 'calculation': [AutomaticCalculation.RelacaoCN],
        'metric': 'g kg⁻¹',
        'max': 1000,
        'name': 'C',
        'label': 'C orgânico',
        'placeholder': 'Informe o valor'
    },
    'N': {
        'type': 67,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'metric': 'g kg⁻¹',
        'max': 500,
        // 'calculation': [AutomaticCalculation.RelacaoCN],
        'name': 'N',
        'label': 'N',
        'placeholder': 'Informe o valor'
    },
    'CN': {
        'type': 68,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'max': 50,
        'name': 'CN',
        'label': 'Relação C/N',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoCA': {
        'type': 54,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'cmolc kg⁻¹',
        'max': 50,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoS],
        'decimal': 1,
        'name': 'ComplexoSortidoCA',
        'label': 'Ca²⁺',
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoMG': {
        'type': 55,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'cmol𝖼 kg⁻¹',
        'max': 50,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoS],
        'decimal': 1,
        'name': 'ComplexoSortidoMG',
        'label': 'Mg²⁺',
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoK': {
        'type': 56,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'metric': 'cmolc kg⁻¹',
        'max': 5,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoS],
        'name': 'ComplexoSortidoK',
        'label': 'K⁺',
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoNa': {
        'type': 57,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 2,
        'metric': 'cmolc kg⁻¹',
        'max': 25,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoS, AutomaticCalculation.SaturacaoSodio],
        'name': 'ComplexosortidoNa',
        'label': 'Na⁺',
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoS': {
        'type': 58,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'cmolc kg⁻¹',
        'max': 100,
        'decimal': 1,
        'name': 'ComplexoSortidoS',
        'label': 'Valor S',
        'editable': false,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoT, AutomaticCalculation.ComplexoSortidoV, AutomaticCalculation.SaturacaoAluminio],
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoAI': {
        'type': 59,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'cmolc kg⁻¹',
        'max': 25,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoT, AutomaticCalculation.SaturacaoAluminio],
        'decimal': 1,
        'name': 'ComplexoSortidoAI',
        'label': 'Al³⁺',
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoH': {
        'type': 60,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'cmolc kg⁻¹',
        'max': 25,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoT],
        'decimal': 1,
        'name': 'ComplexoSortidoH',
        'label': 'H⁺',
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoT': {
        'type': 61,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'cmolc kg⁻¹',
        'max': 100,
        // 'calculation': [AutomaticCalculation.ComplexoSortidoV, AutomaticCalculation.SaturacaoSodio],
        'decimal': 1,
        'name': 'ComplexoSortidoT',
        'label': 'Valor T',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoV': {
        'type': 62,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': '%',
        'max': 100,
        'decimal': 1,
        'name': 'ComplexoSortidoV',
        'label': 'Valor V',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'SaturacaoAluminio': {
        'type': 63,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': '%',
        'max': 100,
        'decimal': 1,
        'name': 'SaturacaoAluminio',
        'label': 'Saturação por Al³⁺',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'ComplexoSortidoP': {
        'type': 64,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'mg kg⁻¹',
        'max': 3000,
        'decimal': 1,
        'name': 'ComplexoSortidoP',
        'label': 'P assimilável',
        'placeholder': 'Informe o valor'
    },
    'AtaqueSulfúricoSiO2': {
        'type': 69,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': 'g kg⁻¹',
        'max': 1000,
        // 'calculation': [AutomaticCalculation.RelacaoKI, AutomaticCalculation.RelacaoKR],
        'name': 'AtaqueSulfúricoSiO2',
        'label': 'Ataque sulfúrico (SiO₂)',
        'placeholder': 'Informe o valor'
    },
    'AtaqueSulfúricoAl2O3': {
        'type': 70,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': 'g kg⁻¹',
        'max': 1000,
        // 'calculation': [AutomaticCalculation.RelacaoKI, AutomaticCalculation.RelacaoKR, AutomaticCalculation.RelacaoAl2O3FE2O3],
        'name': 'AtaqueSulfúricoAl2O3',
        'label': 'Ataque sulfúrico (Al₂O₃)',
        'placeholder': 'Informe o valor'
    },
    'AtaqueSulfúricoFe2O3': {
        'type': 71,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': 'g kg⁻¹',
        'max': 750,
        // 'calculation': [AutomaticCalculation.RelacaoKR, AutomaticCalculation.RelacaoAl2O3FE2O3],
        'name': 'AtaqueSulfúricoFe2O3',
        'label': 'Ataque sulfúrico (Fe₂O₃)',
        'placeholder': 'Informe o valor'
    },
    'AtaqueSulfúricoTiO2': {
        'type': 72,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'g kg⁻¹',
        'max': 100,
        'decimal': 1,
        'name': 'AtaqueSulfúricoTiO2',
        'label': 'Ataque Sulfúrico (TiO₂)',
        'placeholder': 'Informe o valor'
    },
    'AtaqueSulfúricoP2O5': {
        'type': 73,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'g kg⁻¹',
        'max': 10,
        'decimal': 1,
        'name': 'AtaqueSulfúricoP2O5',
        'label': 'Ataque Sulfúrico (P₂O₅)',
        'placeholder': 'Informe o valor'
    },
    'AtaqueSulfúricoMnO': {
        'type': 74,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'g kg⁻¹',
        'max': 10,
        'decimal': 1,
        'name': 'AtaqueSulfúricoMnO',
        'label': 'Ataque Sulfúrico (MnO)',
        'placeholder': 'Informe o valor'
    },
    'RelaçõesMolecularesSiO2AI2O3': {
        'type': 75,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 10,
        'decimal': 2,
        'name': 'RelaçõesMolecularesSiO2AI2O3',
        'label': 'Ki (SiO₂/AI₂O₃)',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'RelaçõesMolecularesSiO2R2O3': {
        'type': 76,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 10,
        'decimal': 2,
        'name': 'RelaçõesMolecularesSiO2R2O3',
        'label': 'Kr (SiO₂/R₂O₃)',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'RelaçõesMolecularesAl2O3Fe2O3': {
        'type': 77,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'max': 10,
        'decimal': 2,
        'name': 'RelaçõesMolecularesAlO3Fe2O3',
        'label': 'Relação Al₂O₃/Fe₂O₃',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'Fe2O3 livre': {
        'type': 91,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': 'g kg⁻¹',
        'max': 1000,
        'name': 'Fe2O3 livre',
        'label': 'Fe₂O₃ livre',
        'placeholder': 'Informe o valor'
    },
    'EquivalenteCaCO': {
        'type': 78,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': 'g kg⁻¹',
        'max': 1000,
        'name': 'EquivalenteCaCO',
        'label': 'Equivalente de CaCO₃',
        'placeholder': 'Informe o valor'
    },
    'SaturacaoSodio': {
        'type': 65,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': 'mg kg⁻¹',
        'max': 100,
        'decimal': 1,
        'name': 'SaturacaoSodio',
        'label': 'Saturação por Na⁺',
        'editable': false,
        'placeholder': 'Informe o valor'
    },
    'PastaSaturadaCEExtrato': {
        'type': 79,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'metric': 'dS/m',
        'decimal': 1,
        'max': 50,
        'name': 'PastaSaturadaCEExtrato',
        'label': 'Condutividade Elétrica',
        'placeholder': 'Informe o valor'
    },
    'PastaSaturadaAgua': {
        'type': 80,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number-pad',
        'metric': '%',
        'max': 100,
        'name': 'PastaSaturadaAgua',
        'label': 'Água (pasta saturada)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisCa2': {
        'type': 81,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 20,
        'name': 'SaisSolúveisCa2',
        'label': 'Sais Solúveis (Ca²⁺)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisMg2': {
        'type': 82,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 20,
        'name': 'SaisSolúveisMg2',
        'label': 'Sais Solúveis (Mg²⁺)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisK': {
        'type': 83,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 10,
        'name': 'SaisSolúveisK',
        'label': 'Sais Solúveis (K⁺)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisNa': {
        'type': 84,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 30,
        'name': 'SaisSolúveisNa',
        'label': 'Sais Solúveis (Na⁺)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisHCO3': {
        'type': 86,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 10,
        'name': 'SaisSolúveisHCO3',
        'label': 'Sais Solúveis (HCO₃⁻)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisCO32': {
        'type': 87,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 10,
        'name': 'SaisSoluveisCO32',
        'label': 'Sais Solúveis (CO₃²⁻)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisCl': {
        'type': 88,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 30,
        'name': 'SaisSolúveisCl',
        'label': 'Sais Solúveis (Cl⁻)',
        'placeholder': 'Informe o valor'
    },
    'SaisSoluveisSO42': {
        'type': 89,
        'maxLength': 4,
        'inputType': 1,
        'keyboardType': 'number',
        'decimal': 1,
        'metric': 'cmolc kg⁻¹',
        'max': 20,
        'name': 'SaisSoluveisSO42',
        'label': 'Sais Solúveis (SO₄²⁻)',
        'placeholder': 'Informe o valor'
    }
}
